files: 2022/nathans106/.*
repos:
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: python 2022/nathans106/ci/fmt.py
        language: system
        types: [rust]
    -   id: cargo-check
        name: cargo-check
        entry: python 2022/nathans106/ci/check.py
        language: system
        types: [rust]
    -   id: clippy
        name: clippy
        entry: python 2022/nathans106/ci/clippy.py
        language: system
        types: [rust]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
