[package]
name = "nathans106"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-01"

[[bin]]
name = "day-02"

[[bin]]
name = "day-03"

[[bin]]
name = "day-04"

[[bin]]
name = "day-05"

[[bin]]
name = "day-06"

[dependencies]
itertools = "0.10.5"
regex = "1.7.0"
